import { KashifDiagnosticReport } from "./types";

export const SAMPLE_TOYOTA_COROLLA: KashifDiagnosticReport = {
  reportId: "kashif-corolla-2004-wa0001",
  generatedAt: "2026-08-21T00:27:39.000Z",
  scannerInfo: {
    toolName: "Ediag OBD-II Scanner",
    serialNumber: "SN-SAMPLE-0000",
    testTime: "08/21/2026 00:27:39",
  },
  vehicle: {
    vin: "JTDBR42E309SAMPLE",
    make: "Toyota",
    model: "Corolla",
    year: "2004",
    mileage: "185,000 كم (تقديري)",
    engineSpecs: {
      displacement: "1.8L 1ZZ-FE (4 سلندر)",
      fuelType: "بنزين",
      cylinders: 4,
      transmission: "كمبيو أوتوماتيك 4 سرعات (كونفيرتا)",
    },
  },
  summary: {
    overallHealthScore: 84,
    severityStatus: "متوسط / انتبه",
    briefSummaryArabic:
      "السيارة حالتها جيدة عموماً ومافيش مشاكل ميكانيكية خطيرة في المحرك أو الكمبيو. العطل الرئيسي متمركز في حساس الماف (حساس الهواء) الراكب على قربة فيلترو الهواء قبل راس الانجكشن، مسبب تفتفة وخنقة خفيفة في العزم مع ولعة لامبة تشك (Check Engine). باب السائق فيه كود كهربائي قديم في الذاكرة للسنتر لوك.",
    systemsCheckedCount: 4,
    faultsFoundCount: 3,
    passedSystemsCount: 3,
  },
  faultCategories: {
    criticalFaults: [],
    moderateFaults: [
      {
        code: "P0102",
        module: "ECM",
        moduleNameArabic: "كمبيوتر المحرك (ECM)",
        standardDescriptionEn: "Mass Air Flow (MAF) Circuit Low Input",
        libyanTerm: "حساس الماف / حساس الهواء (قبل راس الانجكشن)",
        standardArabicDescription: "انخفاض إشارة جهد دائرة مستشعر كتلة تدفق الهواء",
        driverSymptoms: [
          "تفتفة ورعشة خفيفة عند الوقوف في المارشا",
          "خنقة وضعف في العزم والتسارع عند الدعس المفاجئ",
          "ولعة لامبة تشك (Check Engine) في الكوادرو",
          "زيادة ملحوظة في استهلاك البنزين",
        ],
        rootCauses: [
          "اتساخ سلك الاستشعار داخل حساس الماف بالزيوت والغبار",
          "خلل أو كسر في فيشة الحساس أو خيوط البيانتو (Wiring Harness)",
          "تلف داخلي في حساس الماف (MAF Sensor)",
          "انسداد فيلترو الهواء أو اتساخ بوابة راس الانجكشن وتسريب هواء من المناكوطي",
        ],
        urgencyLevel: "متوسط",
        impactOnVehicle: {
          safety: "منخفض",
          fuelEconomy: "متأثر",
          drivability: "عزم ضعيف / تفتفة",
        },
        recommendedAction:
          "نظف سلك الحساس بسبراي تنظيف إلكترونيات مخصص (Contact Cleaner) ونظف بوابة راس الانجكشن وفيلترو الهواء وتأكد من سلامة فيشة البيانتو قبل شراء حساس جديد.",
        recommendedPartId: "part-maf-toyota",
      },
      {
        code: "P0113",
        module: "ECM",
        moduleNameArabic: "كمبيوتر المحرك (ECM)",
        standardDescriptionEn: "Intake Air Temperature (IAT) Sensor Circuit High Input",
        libyanTerm: "حساس حرارة هواء السحب (مدمج في حساس الماف)",
        standardArabicDescription: "ارتفاع جهد إشارة مستشعر درجة حرارة هواء السحب",
        driverSymptoms: [
          "صعوبة خفيفة في التشغيل الصباحي أو عند برودة المحرك",
          "قراءة غير دقيقة لحرارة الهواء ترسل للكمبيوتر فيزيد ضخ البنزين في الرشاشات",
        ],
        rootCauses: [
          "فيشة حساس الماف مفصولة أو غير محكمة التثبيت",
          "تلف مقاومة الثيرمستور المدمجة داخل نفس قطعة حساس الماف",
          "قطع في خيط التغذية الأرضي للحساس في البيانتو",
        ],
        urgencyLevel: "متوسط",
        impactOnVehicle: {
          safety: "منخفض",
          fuelEconomy: "متأثر",
          drivability: "عزم ضعيف / تفتفة",
        },
        recommendedAction:
          "هذا الحساس مدمج داخلياً بنفس قطعة كود P0102. بمجرد صيانة أو استبدال حساس الماف وتثبيت الفيشة سيختفي الكودان معاً وتنطفي لامبة تشك.",
        recommendedPartId: "part-maf-toyota",
      },
    ],
    minorOrHistoricalFaults: [
      {
        code: "B2321",
        module: "BCM",
        moduleNameArabic: "كمبيوتر الهيكل والراحة (BCM)",
        standardDescriptionEn: "Driver Door Motor ECU Communication Stop (History)",
        libyanTerm: "موتور باب السائق / السنتر لوك وسكة المرش",
        standardArabicDescription: "توقف مؤقت في اتصال وحدة محرك باب السائق (كود محفوظ سابقاً)",
        driverSymptoms: [
          "تأخر طفيف سابق في استجابة قفل السنتر لوك من مفتاح الباب",
          "الكود مسجل كـ History (قديم) وغالباً لا يؤثر على القيادة الآن",
        ],
        rootCauses: [
          "فصل بطارية السيارة (المورسيتي) سابقاً أو ضعف مؤقت في الفولتية",
          "ارتخاء فيشة أسلاك باب السائق المارة بجانب الفخدة الأمامية",
        ],
        urgencyLevel: "منخفض",
        impactOnVehicle: {
          safety: "منخفض",
          fuelEconomy: "غير متأثر",
          drivability: "قيادة طبيعية",
        },
        recommendedAction:
          "تصفير الكود بجهاز الكشف (Clear DTC) واختبر عمل سكة المرش وقفل السنتر لوك.",
      },
    ],
  },
  passedSystems: [
    { systemCode: "AC", systemNameArabic: "دورة التكييف والكمبريسوري", systemNameEnglish: "Air Conditioning System" },
    { systemCode: "RCC", systemNameArabic: "نظام تثبيت السرعة والردار", systemNameEnglish: "Radar Cruise Control" },
    { systemCode: "DDM", systemNameArabic: "وحدة محرك باب السائق", systemNameEnglish: "Driver Door Motor (Active State)" },
  ],
  sparePartsRequired: [
    {
      id: "part-maf-toyota",
      relatedCode: "P0102 / P0113",
      partNameLibyan: "حساس الماف / حساس الهواء (Toyota Corolla)",
      partNameStandardArabic: "مستشعر تدفق الهواء وحرارة السحب",
      partNameEnglish: "Mass Air Flow Sensor (MAF)",
      oemPartNumber: "22204-22010",
      aftermarketReplacements: [
        "Denso 197-6030 (الأصلي المعتمد لتويوتا)",
        "Bosch 0280218xxx",
        "Mobiletron MA-T001",
      ],
      estimatedPriceRangeLYD: {
        min: 80,
        max: 230,
        marketNote: "التجاري الياباني/التايواني يبدأ من 80-120 د.ل، والأصلي دينسو رابش نظيف/جديد 180-230 د.ل في سوق الجمعة أو شارع عمر المختار / رابش الدائري والسواني",
      },
      diagramCategory: "المحرك",
    },
    {
      id: "part-air-filter-toyota",
      relatedCode: "P0102",
      partNameLibyan: "فيلترو هواء المحرك",
      partNameStandardArabic: "مرشح هواء المحرك",
      partNameEnglish: "Engine Air Filter",
      oemPartNumber: "17801-0D010",
      aftermarketReplacements: ["Denso 143-2060", "Mann C26003", "Fram CA9392"],
      estimatedPriceRangeLYD: {
        min: 25,
        max: 60,
        marketNote: "متوفر بكثرة في كافة محلات قطع الغيار والسيرفيز السريع",
      },
      diagramCategory: "المحرك",
    },
  ],
  workshopChecklist: [
    {
      stepNumber: 1,
      targetComponent: "فيشة حساس الماف (البيانتو)",
      actionRequiredLibyan: "افحص كليبس الفيشة وتأكد إنها راكبة ومحبكة ومافيش خيوط مقروصة أو مكسورة في البيانتو.",
      toolNeeded: "فحص بالعين المجردة + بنسة",
      isCompleted: false,
    },
    {
      stepNumber: 2,
      targetComponent: "تنظيف سلك حساس الماف وبوابة راس الانجكشن",
      actionRequiredLibyan: "فك المسمارين وطلع الحساس ونظف السلك الداخلي بلطف بسبراي Contact Cleaner ونظف بوابة راس الانجكشن.",
      toolNeeded: "مفك كاتشافيتي صليبة + سبراي تنظيف",
      isCompleted: false,
    },
    {
      stepNumber: 3,
      targetComponent: "فيلترو الهواء ومناكوطي السحب",
      actionRequiredLibyan: "افتح قربة الفيلترو ونظفها من الغبار، وتأكد من سلامة الخرطوم (المناكوطي) وعدم وجود أي شق يسرب هواء كاذب.",
      toolNeeded: "فحص يدوي",
      isCompleted: false,
    },
    {
      stepNumber: 4,
      targetComponent: "تصفير الأعطال واختبار اللايف داتا",
      actionRequiredLibyan: "تصفير لامبة تشك بـ جهاز الكشف وشغل السيارة وشوف قراءة تدفق الهواء (MAF g/s) لازم تكون بين 1.8 إلى 2.5 جم/ث عند الوقوف.",
      toolNeeded: "جهاز كشف OBD Scanner",
      isCompleted: false,
    },
  ],
};

export const SAMPLE_BMW_528I: KashifDiagnosticReport = {
  reportId: "kashif-bmw-528i-wa0026",
  generatedAt: "2026-08-12T21:12:55.000Z",
  scannerInfo: {
    toolName: "Ediag All-System Scanner",
    serialNumber: "SN-SAMPLE-0000",
    testTime: "08/12/2026 21:12:55",
  },
  vehicle: {
    vin: "WBADD6100VBSAMPLE",
    make: "BMW",
    model: "528i (E39)",
    year: "1997.07",
    mileage: "280,911 Miles (~452,000 كم)",
    engineSpecs: {
      displacement: "2.8L M52B28 (6 سلندر مستقيم)",
      fuelType: "بنزين",
      cylinders: 6,
      transmission: "كمبيو أوتوماتيك ZF 5HP18 (كونفيرتا Steptronic)",
    },
  },
  summary: {
    overallHealthScore: 48,
    severityStatus: "حرج / خطر",
    briefSummaryArabic:
      "السيارة فيها عدة أعطال متراكمة تحتاج صيانة جادة: أولاً خلل إشعال في السلندر الرابع (بوبينة أو شمعة) مسبب رجفة في الموتوري وضعف عزم مع ولعة لامبة تشك، ثانياً عطل في حساسات وسلك سرعة العجلات ونظام الـ ABS والـ ASC مما يفصل مانع الانزلاق ويؤثر على تبديلات الكمبيو والكونفيرتا، بالإضافة لعطل في حساس مستوى الزيت في الستاقوبا وعوامات خزان البنزين وسويتش لمبة الستوب وحساسات المرميطة.",
    systemsCheckedCount: 12,
    faultsFoundCount: 28,
    passedSystemsCount: 6,
  },
  faultCategories: {
    criticalFaults: [
      {
        code: "ECM 02",
        module: "ECM (DME)",
        moduleNameArabic: "كمبيوتر المحرك (DME)",
        standardDescriptionEn: "Ignition Coil / Misfire Cylinder 4",
        libyanTerm: "بوبينة وشمعات السلندر الرابع (البسطوني 4)",
        standardArabicDescription: "خلل في دائرة إشعال واحتراق الاسطوانة رقم 4",
        driverSymptoms: [
          "رعشة قوية واهتزاز في المحرك عند الوقوف وأثناء التسارع (تفتفة)",
          "سقوط حاد في عزم المحرك وصعوبة صعود المرتفعات",
          "رائحة بنزين ني غير محترق تخرج من المرميطة",
          "ولعة لامبة تشك (Check Engine) متقطعة أو ثابتة",
        ],
        rootCauses: [
          "تلف بوبينة الإشعال للسلندر رقم 4 (Ignition Coil)",
          "تآكل أو احتراق وتراكم كربون وزيت على الشمعة (Spark Plug)",
          "تسريب زيت من قرسيوني كوبيركو (حشية غطاء الصمامات) غارق البوبينة بالزيت",
        ],
        urgencyLevel: "عالي جداً",
        impactOnVehicle: {
          safety: "متوسط",
          fuelEconomy: "متأثر",
          drivability: "خطر على المحرك",
        },
        recommendedAction:
          "فك بوبينة السلندر 4 والشمعة، تأكد من عدم وجود زيت من قرسيوني الكوبيركو، واستبدل البوبينة أو الشمعة فوراً لحماية المحرك وعلبة كربون المرميطة.",
        recommendedPartId: "part-bmw-coil",
      },
      {
        code: "ABS 21",
        module: "ABS/DSC",
        moduleNameArabic: "منظومة الفرامل المانعة للانغلاق (ABS / DSC)",
        standardDescriptionEn: "Wheel-Speed-Sensor Wire, Front Left, Faulty",
        libyanTerm: "خيوط وسلك حساس سرعة العجلة الأمامية يسار (ABS)",
        standardArabicDescription: "تلف في سلك ومستشعر سرعة العجلة الأمامية اليسرى",
        driverSymptoms: [
          "ولعة لمبة الـ ABS ولمبة مثلث مانع الانزلاق (ASC/DSC) في الكوادرو",
          "تعطل نظام الفرامل المانع للانغلاق وعودة الفرامل للنظام التقليدي",
          "تأثير مباشر على إشارة السرعة المرسلة لكمبيوتر الكمبيو والمحرك",
        ],
        rootCauses: [
          "تآكل أو قطع في سلك الحساس بسبب حركة الصالة والمزاطوري",
          "تلف كبسولة الحساس الكهرومغناطيسي على موتسو العجلة",
          "تراكم برادة حديد وأوساخ حول حلقة الـ ABS في الكوشينتي",
        ],
        urgencyLevel: "عالي جداً",
        impactOnVehicle: {
          safety: "عالي",
          fuelEconomy: "غير متأثر",
          drivability: "عزم ضعيف / تفتفة",
        },
        recommendedAction:
          "افحص سلك الحساس المار بجانب الصالة والمزاطوري الأيسر، واستبدل الحساس إذا كان السلك متآكلاً.",
        recommendedPartId: "part-bmw-abs-sensor",
      },
      {
        code: "TCM 29 / ABS 05",
        module: "TCM / ABS",
        moduleNameArabic: "كمبيوتر الكمبيو والفرامل",
        standardDescriptionEn: "Wheel Speed Rear Right Not Plausible",
        libyanTerm: "حساس سرعة العجلة الخلفية يمين (كوشينتي / موتسو العجلة)",
        standardArabicDescription: "قراءة غير منطقية من مستشعر سرعة العجلة الخلفية اليمنى",
        driverSymptoms: [
          "تأخر في تعشيقات الكمبيو الأوتوماتيك والكونفيرتا أو نتعة عند نقل المارشا",
          "توقف عداد السرعة في الكوادرو أحياناً",
        ],
        rootCauses: [
          "عطل في حساس العجلة الخلفية يمين",
          "تلف أو تأكل في كوشينتي العجلة الخلفية (البيرنغ)",
        ],
        urgencyLevel: "عالي جداً",
        impactOnVehicle: {
          safety: "عالي",
          fuelEconomy: "غير متأثر",
          drivability: "عزم ضعيف / تفتفة",
        },
        recommendedAction:
          "فحص الحساس والكوشينتي وتنظيف مكان التركيب في موتسو العجلة الخلفية.",
        recommendedPartId: "part-bmw-abs-rear",
      },
    ],
    moderateFaults: [
      {
        code: "ECM CB / CA",
        module: "ECM",
        moduleNameArabic: "كمبيوتر المحرك (DME)",
        standardDescriptionEn: "Oxygen-Sensor Control Limit Cylinders 1-3 & 4-6",
        libyanTerm: "حساسات المرميطة العلوية والسفلية (حساسات الأكسجين في الكوليتوري)",
        standardArabicDescription: "تجاوز حد التحكم في خليط الوقود لحساسات مرميطة العادم",
        driverSymptoms: [
          "صرفية بنزين مرتفعة جداً",
          "دخان أسود خفيف ورائحة كربون عند الدعس القوي",
        ],
        rootCauses: [
          "تسريب هواء من خراطيم الفاكيوم أو مناكوطي بوابة راس الانجكشن",
          "تلف أو ضعف في قراءات حساسات المرميطة قبل أو بعد علبة الكربون",
        ],
        urgencyLevel: "متوسط",
        impactOnVehicle: {
          safety: "منخفض",
          fuelEconomy: "متأثر",
          drivability: "عزم ضعيف / تفتفة",
        },
        recommendedAction: "افحص تسريب الهواء في خراطيم المحرك بسبراي الدخان قبل تغيير حساسات المرميطة.",
      },
      {
        code: "LSZ 28",
        module: "LSZ/LCM",
        moduleNameArabic: "كمبيوتر الإضاءة والمراقبة (LCM)",
        standardDescriptionEn: "Thermal Sensor For Oil Level Defective",
        libyanTerm: "حساس مستوى وحرارة الزيت (في الستاقوبا)",
        standardArabicDescription: "عطل في المستشعر الحراري لمستوى زيت المحرك في الكرتير",
        driverSymptoms: [
          "ولعة لمبة الزيت الصفراء في الكوادرو بعد إطفاء المحرك ببضع ثوانٍ",
          "عدم تنبيه السائق عند انخفاض مستوى الزيت الحقيقي",
        ],
        rootCauses: [
          "تلف الحساس المركب أسفل ستاقوبا زيت المحرك",
          "اتساخ الحساس بالرواسب والزيوت القديمة",
        ],
        urgencyLevel: "متوسط",
        impactOnVehicle: {
          safety: "متوسط",
          fuelEconomy: "غير متأثر",
          drivability: "قيادة طبيعية",
        },
        recommendedAction: "استبدال الحساس السفلي عند موعد تغيير الزيت القادم (تفريغ زيت الستاقوبا).",
        recommendedPartId: "part-bmw-oil-sensor",
      },
      {
        code: "LSZ 14",
        module: "LSZ/LCM",
        moduleNameArabic: "كمبيوتر الإضاءة والتحكم",
        standardDescriptionEn: "Brake Light Switch Wire Open",
        libyanTerm: "سويتش لمبة الستوب (فوق دواسة الفرينو)",
        standardArabicDescription: "دائرة مفتوحة في سلك مفتاح أضواء التوقف الخلفية",
        driverSymptoms: [
          "عدم إضاءة لمبات الستوب الخلفية عند الضغط على الفرامل أو بقائها مضاءة باستمرار",
        ],
        rootCauses: [
          "تلف السويتش الصغير فوق دواسة الفرامل أو ارتخاء فيشته في البيانتو",
        ],
        urgencyLevel: "متوسط",
        impactOnVehicle: {
          safety: "عالي",
          fuelEconomy: "غير متأثر",
          drivability: "قيادة طبيعية",
        },
        recommendedAction: "استبدال سويتش دعسة الفرامل لتفادي حوادث الاصطدام الخلفي.",
      },
    ],
    minorOrHistoricalFaults: [
      {
        code: "IC D7 / C7",
        module: "IC",
        moduleNameArabic: "لوحة العدادات (الكوادرو)",
        standardDescriptionEn: "Tank Sensor 1 & 2 (Fuel Level Senders)",
        libyanTerm: "عوامات خزان البنزين (جهة البومبة والجهة الثانية)",
        standardArabicDescription: "عطل في مستشعرات قياس كمية الوقود في الخزان",
        driverSymptoms: [
          "قراءة غير دقيقة لمؤشر البنزين في الكوادرو",
        ],
        rootCauses: ["تآكل مسارات الكربون في عوامات خزان الوقود"],
        urgencyLevel: "منخفض",
        impactOnVehicle: {
          safety: "منخفض",
          fuelEconomy: "غير متأثر",
          drivability: "قيادة طبيعية",
        },
        recommendedAction: "تنظيف أو استبدال عوامة البنزين عند فك بومبة البنزين.",
      },
      {
        code: "SRS 18",
        module: "SRS",
        moduleNameArabic: "منظومة الوسائد الهوائية (الإيرباق)",
        standardDescriptionEn: "Passenger Seat Occupancy Detector",
        libyanTerm: "حساس إشغال كرسي الراكب (سنسور الإيرباق)",
        standardArabicDescription: "عطل في حساس شريحة مقعد الراكب الأمامي",
        driverSymptoms: ["ولعة لمبة الإيرباق في الكوادرو باستمرار"],
        rootCauses: ["كسر في مسارات شريحة المقعد المطاطية داخل الكرسي"],
        urgencyLevel: "منخفض",
        impactOnVehicle: {
          safety: "متوسط",
          fuelEconomy: "غير متأثر",
          drivability: "قيادة طبيعية",
        },
        recommendedAction: "تركيب شريحة محاكاة (Bypass Emulator) أو استبدال سنسور الكرسي.",
      },
    ],
  },
  passedSystems: [
    { systemCode: "EWS", systemNameArabic: "منظومة الحماية ومانع السرقة", systemNameEnglish: "Electronic Immobilizer System" },
    { systemCode: "RAD", systemNameArabic: "الراديو والنظام الصوتي", systemNameEnglish: "Radio & Sound System" },
    { systemCode: "ZKE", systemNameArabic: "سنتر الهيكل وقفل الأبواب", systemNameEnglish: "Central Body Electronic Module" },
    { systemCode: "A/C", systemNameArabic: "نظام التكييف والتحكم بالمناخ (IHKA)", systemNameEnglish: "Air Conditioning Climate Control" },
    { systemCode: "MFL", systemNameArabic: "أزرار عجلة القيادة (الستيرسو)", systemNameEnglish: "Multi-Function Steering Wheel" },
    { systemCode: "MID", systemNameArabic: "شاشة المعلومات المتعددة", systemNameEnglish: "Multi Information Display" },
  ],
  sparePartsRequired: [
    {
      id: "part-bmw-coil",
      relatedCode: "ECM 02",
      partNameLibyan: "بوبينة إشعال BMW E39 (سلندر 4)",
      partNameStandardArabic: "ملف إشعال المحرك (الكويل)",
      partNameEnglish: "Ignition Coil (Bremi / Bosch)",
      oemPartNumber: "12131748017 / 12137599219",
      aftermarketReplacements: ["Bremi 11860T", "Bosch 0221504029", "NGK 48004", "Delphi GN10328"],
      estimatedPriceRangeLYD: {
        min: 90,
        max: 220,
        marketNote: "بريما / بوش جديد في محلات بيع قطع الألماني حوالي 140-200 د.ل، أو رابش أصلي 60-90 د.ل في رابش السواني أو الدائري",
      },
      diagramCategory: "المحرك",
    },
    {
      id: "part-bmw-abs-sensor",
      relatedCode: "ABS 21",
      partNameLibyan: "حساس ABS أمامي يسار BMW E39",
      partNameStandardArabic: "مستشعر سرعة العجلة الأمامية",
      partNameEnglish: "Front Left ABS Wheel Speed Sensor",
      oemPartNumber: "34521182159",
      aftermarketReplacements: ["ATE 24.0711-5117.3", "Bosch 0265006321", "Febi Bilstein 09307"],
      estimatedPriceRangeLYD: {
        min: 110,
        max: 260,
        marketNote: "ماركة ATE الألمانية ممتازة ومطابقة للمصنع بـ 190-250 د.ل، متوفر في طريق الشط / تاجوراء والسواني",
      },
      diagramCategory: "الفرامل والعادم",
      partImageUrl: "https://assets.turnermotorsport.com/product_library_tms/1769855_x800.jpg",
    },
    {
      id: "part-bmw-oil-sensor",
      relatedCode: "LSZ 28",
      partNameLibyan: "حساس مستوى الزيت في الستاقوبا",
      partNameStandardArabic: "مستشعر مستوى وحرارة زيت المحرك السفلي",
      partNameEnglish: "Engine Oil Level / Temperature Sensor",
      oemPartNumber: "12617508003",
      aftermarketReplacements: ["Hella 6PR 007 868-031", "VDO S107644001Z", "Meyle 314 881 0000"],
      estimatedPriceRangeLYD: {
        min: 130,
        max: 310,
        marketNote: "ماركة Hella الأصلية بحدود 250 د.ل، يفضل استبداله مع جوان الستاقوبا وزيت السيرفيز الجديد",
      },
      diagramCategory: "المحرك",
      partImageUrl: "https://assets.turnermotorsport.com/product_library_tms/1569654_x800.jpg",
    },
  ],
  workshopChecklist: [
    {
      stepNumber: 1,
      targetComponent: "فحص بوبينة وشمعة السلندر 4",
      actionRequiredLibyan: "بدل بوبينة السلندر 4 مع السلندر 2 وشوف هل العطل ينتقل للسلندر 2 بـ جهاز الكشف؛ إذا انتقل فالبوبينة تالفة، وإذا بقي في 4 افحص الشمعة وخيوط البيانتو.",
      toolNeeded: "مفتاح شمعات + جهاز كشف",
      isCompleted: false,
    },
    {
      stepNumber: 2,
      targetComponent: "سلك حساس الـ ABS الأمامي يسار",
      actionRequiredLibyan: "ارفع السيارة على الكريك واكشف على خيط الحساس وراء الديسكو والمزاطوري، وقيس مقاومة الحساس بالأفوميتر للتأكد من عدم وجود قطع بالسلك.",
      toolNeeded: "كريك + أفوميتر",
      isCompleted: false,
    },
    {
      stepNumber: 3,
      targetComponent: "سويتش لمبة الستوب",
      actionRequiredLibyan: "فك الغطاء تحت التابلو عند دواسة الفرامل، وتأكد من كليبس السويتش واستبدله إذا كانت الأضواء الخلفية لا تعمل.",
      toolNeeded: "مفك كاتشافيتي",
      isCompleted: false,
    },
    {
      stepNumber: 4,
      targetComponent: "فحص تسريب الهواء في دورة السحب",
      actionRequiredLibyan: "رش رذاذ خفيف على مناكوطي الهواء وبوابة راس الانجكشن وخراطيم الفاكيوم لمعرفة مكان دخول الهواء الزائد المسبب لكود CB و CA.",
      toolNeeded: "سبراي كاشف تسريب / Smoke Machine",
      isCompleted: false,
    },
  ],
};
